#!/usr/bin/env bash

# open a browser-based PR for the current branch at the current repo
# assumes github-style URL for creating a PR.
PATH=$(dirname $0)
. "${PATH}/_git-remote.sh"
REPO=$(_github_repo())

BRANCH=$(git symbolic-ref HEAD --short)

x-www-browser "${REPO}/compare/${BRANCH}?expand=1"
