#!/usr/bin/env bash

# open a browser-based PR for the current branch at the current repo
# assumes github-style URL for creating a PR.

REMOTE=origin
REPO=$(git config --local --get remote.${REMOTE}.url)
REPO=${REPO/:/\/}
REPO=${REPO/git@/"https://"}
REPO=${REPO%\.git}

BRANCH=$(git symbolic-ref HEAD --short)

x-www-browser "${REPO}/compare/${BRANCH}?expand=1"
